GET http://127.0.0.1:3000/users/all
###
GET http://127.0.0.1:3000/users/1
###
GET http://127.0.0.1:3000/users/email/turcu.iosif@email.com
###
POST http://127.0.0.1:3000/users
Content-Type: application/json

{"fullName": "Turcu Iosif","password": "password","email": "turcu.iosif@email.com"}

### From here we are talking about posts
GET http://127.0.0.1:3000/posts/all
###
GET http://127.0.0.1:3000/posts/29
###
GET http://127.0.0.1:3000/posts/category/Plumbing
###
POST http://127.0.0.1:3000/posts
Content-Type: application/json

{"title": "Plumbing","description": "I need a plumber","address": "Vasile GOldis","category": "Plumbing","userId": 1, "price": 100, "isNegotiable": true, "isDone": false, "userID": 3 }